config/routes.rb
Rails.application.routes.draw do
  get 'expenses/index'
  get 'expenses/show'
  get 'expenses/new'
  get 'expenses/edit'
  get 'groups/index'
  get 'groups/show'
  get 'groups/new'
  get 'groups/edit'
  get 'home/index'
  get 'search/users', to: 'search#users', as: 'search_users'
  get 'nearby_restaurants', to: 'restaurants#nearby_restaurants'
  get 'search', to: 'restaurants#search'
  devise_for :users
  root 'groups#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :expenses
    resources :expenses
    resources :group_members, only: [:create]
  end
  

  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :users
    has_many :expenses, dependent: :destroy
    has_many :group_members, dependent: :destroy
    has_many :members, through: :group_members, source: :user
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :expenses, dependent: :destroy
  has_many :group_members
  has_many :member_groups, through: :group_members, source: :group

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  # ... other actions ...

  def create
    @expense = @group.expenses.build(expense_params)
    @expense.user = current_user

    if @expense.save
      flash[:notice] = 'Expense was successfully created.'
      redirect_to group_path(@group)
    else
      flash.now[:alert] = 'There was an error creating the expense. Please try again.'
      render 'groups/show'
    end
  end

  # ... other actions ...

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :description, :amount, :due_date, :recurring, :recurrence_frequency)
  end
end

app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_group
  
    def create
      @group_member = @group.group_members.build(user_id: params[:user_id])
  
      if @group_member.save
        flash[:notice] = 'User successfully added to the group.'
      else
        flash[:alert] = 'Unable to add user to the group.'
      end
  
      redirect_to group_path(@group)
    end
  
    private
  
    def set_group
      @group = current_user.groups.find(params[:group_id])
    end
end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = current_user.groups
  end

  def show
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      flash[:notice] = 'Group was successfully created.'
      redirect_to @group
    else
      flash.now[:alert] = 'There was an error creating the group. Please try again.'
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = 'Group was successfully updated.'
      redirect_to @group
    else
      flash.now[:alert] = 'There was an error updating the group. Please try again.'
      render :edit
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = 'Group was successfully deleted.'
      redirect_to groups_path
    else
      flash.now[:alert] = 'There was an error deleting the group. Please try again.'
      render :show
    end
  end

  private

  def set_group
    @group = current_user.groups.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @city = request.location.city
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def search
    end

    def nearby_restaurants
        @restaurants = YelpApiClient.search_nearby_restaurants(params[:latitude], params[:longitude], params[:radius])
    end
      
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :authenticate_user!
  
    def users
      @users = User.where('email LIKE ?', "%#{params[:query]}%")
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<div class="card mb-3">
  <div class="card-header">
    <strong><%= expense.name %></strong>
  </div>
  <div class="card-body">
    <p><%= expense.description %></p>
    <p>Amount: $<%= '%.2f' % expense.amount %></p>
    <p>Due date: <%= expense.due_date.strftime('%Y-%m-%d') %></p>
    <% if expense.recurring %>
      <p>Recurring: <%= expense.recurrence_frequency %></p>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', group_expense_path(expense.group, expense), class: 'btn btn-sm btn-info' %>
    <%= link_to 'Edit', edit_group_expense_path(expense.group, expense), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Delete', group_expense_path(expense.group, expense), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  </div>
</div>

app/views/expenses/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2 class="my-4">Add a New Expense</h2>
      <%= form_with(model: [group, expense], local: true) do |form| %>
        <% if expense.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h4>
            <ul>
              <% expense.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control', rows: 3 %>
        </div>

        <div class="form-group">
          <%= form.label :amount %>
            <div class="input-group">
              <span class="input-group-text">$</span>
              <%= form.number_field :amount, class: 'form-control', step: '0.01' %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :due_date %>
          <%= form.date_field :due_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :recurring %>
          <%= form.check_box :recurring, class: 'form-check-input' %>
        </div>

        <div class="form-group">
          <%= form.label :recurrence_frequency %>
          <%= form.select :recurrence_frequency, options_for_select(['Daily', 'Weekly', 'Monthly', 'Yearly']), { include_blank: 'Select frequency' }, class: 'form-select' %>
        </div>

        <div class="form-group my-3">
          <%= form.submit 'Create Expense', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/expenses/edit.html.erb
<h1>Expenses#edit</h1>
<p>Find me in app/views/expenses/edit.html.erb</p>

app/views/expenses/index.html.erb
<h1>Expenses#index</h1>
<p>Find me in app/views/expenses/index.html.erb</p>

app/views/expenses/new.html.erb
<!-- Render the form partial for creating a new expense -->
<%= render 'expenses/form', group: @group, expense: @group.expenses.build %>

app/views/expenses/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="my-4">Edit Group</h1>

      <%= form_with(model: @group, local: true) do |form| %>
        <% if @group.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h4>
            <ul>
              <% @group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group my-3">
          <%= form.submit 'Update Group', class: 'btn btn-primary' %>
        </div>
      <% end %>

      <%= link_to 'Back to Group', group_path(@group), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="my-4">Your Groups</h1>

      <% if @groups.any? %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |group| %>
              <tr>
                <td><%= group.name %></td>
                <td>
                  <%= link_to 'Show', group_path(group), class: 'btn btn-sm btn-info' %>
                  <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-sm btn-warning' %>
                  <%= link_to 'Delete', group_path(group), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p class="alert alert-info">You have no groups. Create a new one!</p>
      <% end %>

      <%= link_to 'New Group', new_group_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="my-4">Create a New Group</h1>

      <%= form_with(model: @group, local: true) do |form| %>
        <% if @group.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h4>
            <ul>
              <% @group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group my-3">
          <%= form.submit 'Create Group', class: 'btn btn-primary' %>
        </div>
      <% end %>

      <%= link_to 'Back to Groups', groups_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
        <h1 class="my-4">Group Details</h1>

        <table class="table">
            <tbody>
            <tr>
                <th>Name</th>
                <td><%= @group.name %></td>
            </tr>
            <tr>
                <th>Created At</th>
                <td><%= @group.created_at.strftime("%Y-%m-%d %H:%M") %></td>
            </tr>
            <tr>
                <th>Updated At</th>
                <td><%= @group.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
            </tr>
            </tbody>
        </table>

        <div class="my-3">
            <%= link_to 'Edit Group', edit_group_path(@group), class: 'btn btn-primary' %>
            <%= link_to 'New Expense', new_group_expense_path(@group), class: 'btn btn-primary my-3' %>
            <%= link_to 'Invite Users', search_users_path(group_id: @group.id), class: 'btn btn-primary my-3' %>

            <%= button_to 'Delete Group', group_path(@group), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>

        <%= link_to 'Back to Groups', groups_path, class: 'btn btn-secondary' %>
        </div>
    </div>
</div>

<!-- Other content of the show.html.erb file -->
<!-- Other content -->
<div class="row">
    <div class="col-md-6">
        <h2>Group Members</h2>
        <table class="table mt-4">
        <thead>
            <tr>
            <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <% @group.members.each do |member| %>
            <tr>
                <td><%= member.email %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>


<!-- Add this section to render the expense partial for each expense in the group -->
<h2 class="my-4">Expenses</h2>
<% if @group.expenses.any? %>
  <% @group.expenses.each do |expense| %>
    <%= render 'expenses/expense', expense: expense %>
  <% end %>
<% else %>
  <p class="alert alert-info">There are no expenses for this group. Add a new expense!</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer_nav.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container-fluid d-flex flex-wrap justify-content-between">
        <%= link_to search_path, class: 'text-center' do %>
            <i class="fa-solid fa-location-dot" style="color: #09a7f0;"></i>
            <div class="text-muted small">Discover</div>
        <% end %>

        <div class="text-center">
            <i class="fa-solid fa-people-roof" style="color: #09a7f0;"></i>
            <div class="text-muted small">My Crib</div>
        </div>
        <div class="spacer"></div>
        <div class="text-center">
            <i class="fa-solid fa-file-invoice-dollar" style="color: #09a7f0;"></i>
            <div class="text-muted small">Bills</div>
        </div>
        <div class="text-center">
            <i class="fa-solid fa-magnifying-glass-location" style="color: #06b0fa;"></i>
            <div class="text-muted small">Roommates</div>
        </div>
        <div class="new-post-btn">
            <i class="fa-solid fa-plus"></i>
        </div>
    </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <form class="container-fluid">
    <div class="input-group">
      <span class="input-group-text" id="basic-addon1">@</span>
      <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
    </div>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseholdFinanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/footer_nav' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/nearby_restaurants.html.erb
<!-- app/views/restaurants/nearby_restaurants.html.erb -->
<h1>Nearby Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h2><%= restaurant['name'] %></h2>
      <img src="<%= restaurant['image_url'] %>" alt="<%= restaurant['name'] %>" style="width: 200px;">
      <p><%= restaurant['categories'].map { |category| category['title'] }.join(', ') %></p>
      <p>Rating: <%= restaurant['rating'] %></p>
    </li>
  <% end %>
</ul>

app/views/restaurants/search.html.erb
<!-- app/views/restaurants/search.html.erb -->
<h1>Search Nearby Restaurants</h1>

<form id="search-form">
  <label for="radius">Radius (meters):</label>
  <input type="number" id="radius" name="radius" value="8047" min="1">
  <button type="submit">Search</button>
</form>

<div id="restaurants"></div>

<script>
  document.getElementById('search-form').addEventListener('submit', async (event) => {
    event.preventDefault();

    const latitudeInput = document.createElement('input');
    const longitudeInput = document.createElement('input');
    latitudeInput.type = 'hidden';
    longitudeInput.type = 'hidden';
    latitudeInput.name = 'latitude';
    longitudeInput.name = 'longitude';

    try {
      const position = await new Promise((resolve, reject) => {
        navigator.geolocation.getCurrentPosition(resolve, reject);
      });

      latitudeInput.value = position.coords.latitude;
      longitudeInput.value = position.coords.longitude;
    } catch (error) {
      alert('Unable to get your location. Please allow location access.');
      return;
    }

    const form = event.target;
    form.appendChild(latitudeInput);
    form.appendChild(longitudeInput);

    const params = new URLSearchParams(new FormData(form)).toString();
    const response = await fetch(`/nearby_restaurants?${params}`);
    const html = await response.text();

    document.getElementById('restaurants').innerHTML = html;
  });
</script>

app/views/search/users.html.erb
<h1>Search Users</h1>

<%= form_tag search_users_path, method: :get do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search by email" %>
  <%= submit_tag 'Search', class: "btn btn-primary" %>
<% end %>

<table class="table mt-4">
  <thead>
    <tr>
      <th>Email</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <%= form_with(url: group_group_members_path(params[:group_id]), method: :post, local: true) do |form| %>
            <%= form.hidden_field :user_id, value: user.id %>
            <%= form.submit 'Add to Group', class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>